#!/bin/bash

INPUTPATH=./results/LRP_values_raw/epi2000_bih/
OUTPUTPATH=./results/LRP_values_au/epi2000_bih/

##filenames="$(find $INPUTPATH -maxdepth 1 -type f)"
filenames=$(ls $INPUTPATH) 
for f in $filenames
do
    sbatch start_LRPau $INPUTPATH $f $OUTPUTPATH
done



