#!/bin/bash

#SBATCH --job-name=filter_highest
#SBATCH --output=/fast/users/keylpg_c/scratch/tmp/docs/filterhighest-%j.txt
#
#SBATCH --ntasks=1
###SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --time=00:10:00
#SBATCH --mem-per-cpu=4G
#SBATCH --partition=short
echo $1

srun python3 filter_h_i_without_dask.py $1

