#!/bin/bash


#SBATCH --job-name=dascstats
#SBATCH --output=/fast/users/keylpg_c/scratch/tmp/docs/dascstats.txt
#
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=25
#SBATCH --time=7-00:00:00
#SBATCH --mem-per-cpu=6G


python3 dask_stats.py


