#!/bin/bash


#!/bin/bash


#SBATCH --job-name=computeLRP
#SBATCH --output=/fast/users/keylpg_c/scratch/tmp/docs/LRPcomp-%j.txt
#
#SBATCH --ntasks=1
###SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --time=0-04:00:00
#SBATCH --mem-per-cpu=16G
#SBATCH --partition=short

ADDER=10000
srun python3 main_large.py epi2000_bih old $(($SLURM_ARRAY_TASK_ID + $ADDER)) . cpu 0 15
