#!/bin/bash


#SBATCH --job-name=train_network
#SBATCH --output=train_network.txt
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --time=4:00:00
#SBATCH --mem-per-cpu=8G
#SBATCH --partition=gpu
#SBATCH --gres=gpu:tesla:1


python3 main_large.py epi2000_bih new 0 . cpu 1 0


